name: mcMMO-OverhaulQuests
version: 2.2
description: Quests module for mcMMO Overhaul
author: Browsit
website: https://github.com/Browsit/mcMMOQuestsModule

main: org.browsit.mcmmoquests
depend: [mcMMO, Quests]